// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs2477QhyIfwWe3bpayaUQgP998fy6xRk',
    appId: '1:921247764128:web:e8e367828c3272405d03c5',
    messagingSenderId: '921247764128',
    projectId: 'authtech-450308',
    authDomain: 'authtech-450308.firebaseapp.com',
    storageBucket: 'authtech-450308.firebasestorage.app',
    measurementId: 'G-42G7Z9MR0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5i5d30lpqs-5w4nk39DqLs7ZiXZd3QLk',
    appId: '1:921247764128:android:6f06387f01628afe5d03c5',
    messagingSenderId: '921247764128',
    projectId: 'authtech-450308',
    storageBucket: 'authtech-450308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyN2oCfvBSvqBua88eDb-2pCSw1GOC-I',
    appId: '1:921247764128:ios:ca92d5418f5100325d03c5',
    messagingSenderId: '921247764128',
    projectId: 'authtech-450308',
    storageBucket: 'authtech-450308.firebasestorage.app',
    androidClientId: '921247764128-22isf6ga3rdlgcamfv4uct3htuspk351.apps.googleusercontent.com',
    iosClientId: '921247764128-8o2shfi4r57ahm94kblgmvbq2h7dooth.apps.googleusercontent.com',
    iosBundleId: 'com.authentechlite.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'replace-with-your-api-key',
    appId: 'replace-with-your-app-id',
    messagingSenderId: 'replace-with-your-messaging-sender-id',
    projectId: 'replace-with-your-project-id',
    storageBucket: 'replace-with-your-storage-bucket',
    iosBundleId: 'com.example.stampCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'replace-with-your-api-key',
    appId: 'replace-with-your-app-id',
    messagingSenderId: 'replace-with-your-messaging-sender-id',
    projectId: 'replace-with-your-project-id',
    storageBucket: 'replace-with-your-storage-bucket',
    authDomain: 'replace-with-your-auth-domain',
  );
}